[0m14:57:57.428414 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001153D3A8AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011539B15B80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001153D0A3B00>]}


============================== 14:57:57.433309 | e4f9cf7e-f44c-4623-80f2-5f7affdf2d13 ==============================
[0m14:57:57.433309 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:57:57.434309 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\DavidTurcotte\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --select V_RAW_M_TRAFFIC --target prod', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:57:57.435309 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\DavidTurcotte\OneDrive - AppGroup\Desktop\dbtcore\dbt-core-dev\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:57:57.436309 [debug] [MainThread]: Command `dbt run` failed at 14:57:57.435309 after 0.18 seconds
[0m14:57:57.436309 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001153D374920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011539B15B80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001153CA157F0>]}
[0m14:57:57.436309 [debug] [MainThread]: Flushing usage events
[0m14:58:24.875338 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215719A5E80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215719A5850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021574AB4FE0>]}


============================== 14:58:24.888805 | 126ad1b0-43a5-4816-91ca-09170946b80c ==============================
[0m14:58:24.888805 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:58:24.890229 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\DavidTurcotte\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug --config-dir', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:58:24.904314 [info ] [MainThread]: To view your profiles.yml file, run:

start C:\Users\DavidTurcotte\.dbt
[0m14:58:24.905324 [debug] [MainThread]: Command `dbt debug` succeeded at 14:58:24.905324 after 0.18 seconds
[0m14:58:24.905324 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021575294770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215753E1520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215753896D0>]}
[0m14:58:24.906331 [debug] [MainThread]: Flushing usage events
[0m14:58:34.590279 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186D9D53710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186DBFD1880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186D6C19D90>]}


============================== 14:58:34.602397 | 9944f74d-6912-48a5-b4ae-b4ca02e282cc ==============================
[0m14:58:34.602397 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:58:34.603398 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\DavidTurcotte\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --select V_RAW_M_TRAFFIC --target prod', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:58:34.604398 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\DavidTurcotte\OneDrive - AppGroup\Desktop\dbtcore\dbt-core-dev\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:58:34.605400 [debug] [MainThread]: Command `dbt run` failed at 14:58:34.605400 after 0.16 seconds
[0m14:58:34.606410 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186D9D53710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186DB8AB560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186DC3144D0>]}
[0m14:58:34.606410 [debug] [MainThread]: Flushing usage events
[0m13:47:09.914808 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002149D1D37D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002149F7EB9E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002149F47A840>]}


============================== 13:47:09.926561 | 59cb82db-46f6-4325-a6aa-d0599da3db23 ==============================
[0m13:47:09.926561 [info ] [MainThread]: Running with dbt=1.8.7
[0m13:47:09.930632 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\DavidTurcotte\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --select T_SHOPIFY_GC --target prod', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:47:09.931664 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\DavidTurcotte\OneDrive - AppGroup\Desktop\dbtcore\dbt-core-dev\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:47:09.936339 [debug] [MainThread]: Command `dbt run` failed at 13:47:09.935714 after 0.90 seconds
[0m13:47:09.936845 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002149FB26960>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002149D1D37D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002149F010500>]}
[0m13:47:09.938116 [debug] [MainThread]: Flushing usage events
